---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# searchlight_service_names should exclude the API if {{ searchlight_use_mod_wsgi }}
- name: Restart Searchlight services
  service:
    name: "{{ item }}"
    state: "restarted"
    pattern: "{{ item }}"
#  when: not searchlight_use_mod_wsgi | bool
  with_items:
    - "{{ searchlight_listener_program_name }}"
    - "{{ searchlight_api_program_name }}"
